name: Go Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Go
      run: |
        sudo apt update
        sudo apt install -y golang
        go version

    - name: Set up Go environment
      run: |
        mkdir -p $HOME/go/{bin,src,pkg}
        echo "export GOPATH=$HOME/go" >> $HOME/.bashrc
        echo "export PATH=$PATH:$HOME/go/bin" >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Install dependencies
      run: go mod tidy

    - name: Build project
      run: go build -o basic-docker main.go

    - name: Run verification script
      run: |
        chmod +x verify.sh
        ./verify.sh