name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Debug Go version setup
      run: |
        echo "Checking Go version setup..."
        go version
        echo "GOROOT: $GOROOT"
        echo "GOPATH: $GOPATH"
        echo "PATH: $PATH"

    - name: Force Go version installation
      uses: actions/setup-go@v4
      with:
        go-version: 1.20
        check-latest: true

    - name: Ensure correct Go version
      run: |
        go version
        if [[ $(go version) != *"go1.20"* ]]; then
          echo "Error: Incorrect Go version. Expected Go 1.20." && exit 1
        fi

    - name: Install dependencies
      run: go mod tidy

    - name: Build project
      run: go build -o basic-docker main.go

    - name: Run verification script
      run: |
        chmod +x verify.sh
        ./verify.sh